services:
  # Backend Service
  - type: web
    name: note-taking-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        fromDatabase:
          name: notes-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      # Add your email credentials and other env vars manually in Render dashboard

  # Frontend Service  
  - type: web
    name: note-taking-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://note-taking-backend.onrender.com/api
      # Add your Google Client ID manually in Render dashboard

# Database (if using Render's managed MongoDB - optional)
# databases:
#   - name: notes-db
#     plan: free